[2025-07-03T10:31:02.700+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_2_dagv10.load manual__2025-07-03T10:30:26.527428+00:00 [queued]>
[2025-07-03T10:31:02.709+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_2_dagv10.load manual__2025-07-03T10:30:26.527428+00:00 [queued]>
[2025-07-03T10:31:02.709+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-03T10:31:02.746+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-07-03 10:30:26.527428+00:00
[2025-07-03T10:31:02.753+0000] {standard_task_runner.py:60} INFO - Started process 263 to run task
[2025-07-03T10:31:02.756+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'task_2_dagv10', 'load', 'manual__2025-07-03T10:30:26.527428+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/task_2_dag.py', '--cfg-path', '/tmp/tmp63iz9qm1']
[2025-07-03T10:31:02.758+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask load
[2025-07-03T10:31:02.807+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-03T10:31:02.846+0000] {task_command.py:423} INFO - Running <TaskInstance: task_2_dagv10.load manual__2025-07-03T10:30:26.527428+00:00 [running]> on host 86d79be21be1
[2025-07-03T10:31:03.043+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='task_2_dagv10' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T10:30:26.527428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-03T10:30:26.527428+00:00'
[2025-07-03T10:31:03.093+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-07-03T10:31:04.926+0000] {logging_mixin.py:188} INFO - Upload completed.
[2025-07-03T10:31:04.927+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-03T10:31:04.941+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=task_2_dagv10, task_id=load, execution_date=20250703T103026, start_date=20250703T103102, end_date=20250703T103104
[2025-07-03T10:31:05.016+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-03T10:31:05.037+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
